INSERT INTO medicamento (id_medicamento,tipo_medicamento,nombre)
VALUES
  (1,'ruble','Lidoderm'),
  (2,'dram','LevothyroxineSodium'),
  (3,'lempira','Cheratussin AC'),
  (4,'tugrik','Penicillin VK'),
  (5,'pound','Fluconazole'),
  (6,'lek','Diazepam'),
  (7,'kwanza','Niaspan'),
  (8,'quetzal','Fluconazole'),
  (9,'dong','Actos'),
  (10,'rouble','Singulair'),

  (11,'yuan','Citalopram HBr'),
  (12,'ruble','Fluticasone Propionate'),
  (13,'pataca','Lyrica'),
  (14,'sum','Premarin'),
  (15,'yuan','Hydrochlorothiazide'),
  (16,'peso','Hydrochlorothiazide'),
  (17,'kyat','Gabapentin'),
  (18,'rupiah','Paroxetine HCl'),
  (19,'colon','Losartan Potassium'),
  (20,'kuna','Premarin'),

  (21,'lari','Citalopram HBR'),
  (22,'rial','Simvastatin'),
  (23,'yuan','Suboxone'),
  (24,'nuevo sol','Advair Diskus'),
  (25,'kina','Levoxyl'),
  (26,'pataca','Levoxyl'),
  (27,'cedi','Benicar HCT'),
  (28,'dram','Lantus'),
  (29,'koruna','Fluticasone Propionate'),
  (30,'kina','Vytorin'),

  (31,'won','Pantoprazole Sodium'),
  (32,'Danish krone','Tricor'),
  (33,'sterling','Glyburide'),
  (34,'dinar','Meloxicam'),
  (35,'pataca','Sertraline HCl'),
  (36,'ringgit','Glipizide'),
  (37,'krona','Meloxicam'),
  (38,'riel','Sulfamethoxazole/Trimethoprim'),
  (39,'cordoba oro','Vyvanse'),
  (40,'pound','Tricor'),

  (41,'sum','Proair HFA'),
  (42,'baht','Amitriptyline HCl'),
  (43,'kwanza','Namenda'),
  (44,'som','Suboxone'),
  (45,'som','Azithromycin'),
  (46,'tenge','Nuvaring'),
  (47,'ariary','Fluticasone Propionate'),
  (48,'ringgit','Tramadol HCl'),
  (49,'kuna','Alendronate Sodium'),
  (50,'Danish krone','Januvia'),

  (51,'rupiah','Vyvanse'),
  (52,'dollar','Folic Acid'),
  (53,'konvertibilna marka','Vitamin D (Rx)'),
  (54,'dirham','Oxycodone HCl'),
  (55,'somoni','Sertraline HCl'),
  (56,'ringgit','Citalopram HBr'),
  (57,'colon','Niaspan'),
  (58,'baht','Crestor'),
  (59,'pataca','Suboxone'),
  (60,'cordoba oro','Synthroid'),

  (61,'ruble','Seroquel'),
  (62,'Danish krone','APAP/Codeine'),
  (63,'colon','Tramadol HCl'),
  (64,'ruble','Niaspan'),
  (65,'pound','Pravastatin Sodium'),
  (66,'ruble','Flovent HFA'),
  (67,'koruna','Vyvanse'),
  (68,'sterling','Glyburide'),
  (69,'metical','Tricor'),
  (70,'koruna','Vitamin D (Rx)'),

  (71,'hryvnia','Citalopram HBr'),
  (72,'krona','Tramadol HCl'),
  (73,'quetzal','Citalopram HBr'),
  (74,'colon','Nasonex'),
  (75,'rufiyaa','Famotidine'),
  (76,'lilangeni','Vitamin D (Rx)'),
  (77,'rupiah','Clonazepam'),
  (78,'lilangeni','TriNessa'),
  (79,'tugrik','Ibuprofen (Rx)'),
  (80,'guarani','Fluticasone Propionate'),

  (81,'forint',''),
  (82,'escudo','Plavix'),
  (83,'forint','Benicar'),
  (84,'lev','Albuterol'),
  (85,'hryvnia','Lantus'),
  (86,'peso','Januvia'),
  (87,'rufiyaa','Amoxicillin'),
  (88,'lempira','Synthroid'),
  (89,'denar','Ranitidine HCl'),
  (90,'kyat','Triamcinolone Acetonide'),

  (91,'bolivar','Oxycontin'),
  (92,'denar','Seroquel'),
  (93,'krona','Seroquel'),
  (94,'riyal','Lisinopril'),
  (95,'dinar','Oxycontin'),
  (96,'som','Lisinopril'),
  (97,'baht','Citalopram HBr'),
  (98,'kina','Digoxin'),
  (99,'quetzal','Amitriptyline HCl'),
  (100,'euro','Vytorin'),

  (101,'kwanza','Loestrin 24 Fe'),
  (102,'kwanza','Hydrochlorothiazide'),
  (103,'tenge','Namenda'),
  (104,'rupee','Zolpidem Tartrate'),
  (105,'naira','Furosemide'),
  (106,'pound','Metoprolol Succinate'),
  (107,'pound','Warfarin Sodium'),
  (108,'denar','Singulair'),
  (109,'cedi','Venlafaxine HCl ER'),
  (110,'quetzal','Spiriva Handihaler'),

  (111,'rouble','Pravastatin Sodium'),
  (112,'naira','Levaquin'),
  (113,'dollar','Actos'),
  (114,'escudo','Amoxicillin'),
  (115,'franc','Alprazolam'),
  (116,'riyal','Metformin HCl'),
  (117,'nuevo sol','Ciprofloxacin HCl'),
  (118,'lira','Sulfamethoxazole/Trimethoprim'),
  (119,'pula','Gabapentin'),
  (120,'lev','Carisoprodol'),

  (121,'kina','Simvastatin'),
  (122,'lempira','Glyburide'),
  (123,'krona','Tamsulosin HCl'),
  (124,'naira','Citalopram HBr'),
  (125,'yuan','Spiriva Handihaler'),
  (126,'dong','Lovastatin'),
  (127,'Danish krone','Premarin'),
  (128,'tenge','Promethazine HCl'),
  (129,'som','Tramadol HCl'),
  (130,'sterling','Zetia'),

  (131,'kwanza','Prednisone'),
  (132,'tugrik','Famotidine'),
  (133,'riyal','Fluticasone Propionate'),
  (134,'euro','Promethazine HCl'),
  (135,'rupee','Ranitidine HCl'),
  (136,'dollar','Enalapril Maleate'),
  (137,'rupee','Enalapril Maleate'),
  (138,'manat','Oxycodone/APAP'),
  (139,'shekel','Lyrica'),
  (140,'rupiah','Folic Acid'),

  (141,'nuevo sol','Oxycontin'),
  (142,'pula','Januvia'),
  (143,'koruna','Nexium'),
  (144,'rand','Loestrin 24 Fe'),
  (145,'koruna','Omeprazole (Rx)'),
  (146,'pound','Lisinopril'),
  (147,'tugrik','LevothyroxineSodium'),
  (148,'somoni','Lorazepam'),
  (149,'ouguiya','Simvastatin'),
  (150,'manat','Pravastatin Sodium'),

  (151,'shekel','Warfarin Sodium'),
  (152,'rupee','Amlodipine Besylate'),
  (153,'nuevo sol','Enalapril Maleate'),
  (154,'lempira','Benicar HCT'),
  (155,'yuan','Ranitidine HCl'),
  (156,'sterling','Viagra'),
  (157,'yen','Cymbalta'),
  (158,'rial','Naproxen'),
  (159,'yuan','Penicillin VK'),
  (160,'pula','Amoxicillin'),

  (161,'euro','Symbicort'),
  (162,'dollar','Namenda'),
  (163,'kuna','Nasonex'),
  (164,'ariary','Doxycycline Hyclate'),
  (165,'denar','Pravastatin Sodium'),
  (166,'kroner','Vitamin D (Rx)'),
  (167,'yen','Naproxen'),
  (168,'boliviano','Sulfamethoxazole/Trimethoprim'),
  (169,'tenge','Famotidine'),
  (170,'koruna','Simvastatin'),

  (171,'kip','Lexapro'),
  (172,'dollar','Cheratussin AC'),
  (173,'lira','Lantus Solostar'),
  (174,'lira','Amlodipine Besylate'),
  (175,'kina','Zetia'),
  (176,'tenge','Doxycycline Hyclate'),
  (177,'naira','Cheratussin AC'),
  (178,'boliviano','Seroquel'),
  (179,'dong','Vytorin'),
  (180,'pound','Synthroid'),

  (181,'dong','Omeprazole (Rx)'),
  (182,'rouble','Advair Diskus'),
  (183,'rufiyaa','Risperidone'),
  (184,'forint','Lantus Solostar'),
  (185,'denar','Singulair'),
  (186,'nuevo sol','Enalapril Maleate'),
  (187,'bolivar','Amitriptyline HCl'),
  (188,'lempira','Vytorin'),
  (189,'pound','Crestor'),
  (190,'manat','Zetia'),

  (191,'leu','Albuterol'),
  (192,'real','Vyvanse'),
  (193,'rouble','Namenda'),
  (194,'leu','Pravastatin Sodium'),
  (195,'kip','Lisinopril'),
  (196,'rupiah','Benicar HCT'),
  (197,'ariary','Nexium'),
  (198,'rial','Omeprazole (Rx)'),
  (199,'nuevo sol','Cymbalta'),
  (200,'ouguiya','Gabapentin'),

  (201,'dinar','Glipizide'),
  (202,'sterling','Zolpidem Tartrate'),
  (203,'shekel','Pravastatin Sodium'),
  (204,'guarani','Allopurinol'),
  (205,'quetzal','Spiriva Handihaler'),
  (206,'euro','Glipizide'),
  (207,'cordoba oro','Lidoderm'),
  (208,'kuna','Lidoderm'),
  (209,'kroner','Lidoderm'),
  (210,'kina','Amlodipine Besylate'),

  (211,'tugrik','Levothyroxine Sodium'),
  (212,'yuan','Fluticasone Propionate'),
  (213,'kina','Levothyroxine Sodium'),
  (214,'kip','Meloxicam'),
  (215,'kwacha','Metoprolol Succinatee'),
  (216,'manat','Clindamycin HCl'),
  (217,'bolivar','Amlodipine Besylate'),
  (218,'dinar','Cymbalta'),
  (219,'ruble','Januvia'),
  (220,'dinar','Ibuprofen (Rx)'),

  (221,'dram','Crestor'),
  (222,'zloty','Advair Diskus'),
  (223,'ringgit','Crestor'),
  (224,'hryvnia','Ranitidine HCl'),
  (225,'real','Glyburide'),
  (226,'kroner','Cheratussin AC'),
  (227,'lempira','Synthroid'),
  (228,'konvertibilna marka','Diovan'),
  (229,'pataca','Crestor'),
  (230,'franc','Zetia'),

  (231,'dram','Januvia'),
  (232,'kip','Cymbalta'),
  (233,'lek','Lovaza'),
  (234,'kyat','Amitriptyline HCl'),
  (235,'lempira','Penicillin VK'),
  (236,'rufiyaa','Nasonex'),
  (237,'yen','Carisoprodol'),
  (238,'boliviano','Zyprexa'),
  (239,'pound','Gabapentin'),
  (240,'rupee','Loestrin 24 Fe'),

  (241,'sum','Glyburide'),
  (242,'won','Omeprazole (Rx)'),
  (243,'boliviano','LevothyroxineSodium'),
  (244,'rupee','Niaspan'),
  (245,'ariary','Alendronate Sodium'),
  (246,'bolivar','Oxycodone/APAP'),
  (247,'sum','Losartan Potassium'),
  (248,'rial','Fluoxetine HCl'),
  (249,'lilangeni','Spiriva Handihaler'),
  (250,'metical','Oxycodone/APAP'),

  (251,'Danish krone','Amlodipine Besylate'),
  (252,'lev','Lisinopril'),
  (253,'tugrik','Citalopram HBR'),
  (254,'pound','Prednisone'),
  (255,'euro','Lantus'),
  (256,'rupiah','Cyclobenzaprin HCl'),
  (257,'nuevo sol','Metoprolol Succinate'),
  (258,'kwanza','Diovan'),
  (259,'ruble','Advair Diskus'),
  (260,'naira','Fluconazole'),

  (261,'rupiah','Fluoxetine HCl'),
  (262,'ringgit','Zolpidem Tartrate'),
  (263,'som','Glyburide'),
  (264,'pound','Amlodipine Besylate'),
  (265,'kwacha','Endocet'),
  (266,'kip','Metformin HCl'),
  (267,'dram','Oxycontin'),
  (268,'somoni','Plavix'),
  (269,'lempira','Hydrochlorothiazide'),
  (270,'Danish krone','LevothyroxineSodium'),

  (271,'krona','Namenda'),
  (272,'konvertibilna marka','Nuvaring'),
  (273,'dong','Ventolin HFA'),
  (274,'dollar','Namenda'),
  (275,'konvertibilna marka','Bystolic'),
  (276,'pula','Prednisone'),
  (277,'ringgit','Celebrex'),
  (278,'rouble','Lovaza'),
  (279,'som','Carvedilol'),
  (280,'franc','Amlodipine Besylate'),

  (281,'manat','Promethazine HCl'),
  (282,'dollar','Atenolol'),
  (283,'krona','APAP/Codeine'),
  (284,'manat','Actos'),
  (285,'pound','Seroquel'),
  (286,'somoni','Tamsulosin HCl'),
  (287,'dram','Sertraline HCl'),
  (288,'lari','Klor-Con M20'),
  (289,'konvertibilna marka','Benicar HCT'),
  (290,'kroner','Levoxyl'),

  (291,'forint','Tri-Sprintec'),
  (292,'ringgit','Cialis'),
  (293,'pataca','Zolpidem Tartrate'),
  (294,'lari','Glipizide'),
  (295,'ouguiya','Cheratussin AC'),
  (296,'peso','Zyprexa'),
  (297,'denar','Lexapro'),
  (298,'dinar','Pravastatin Sodium'),
  (299,'cordoba oro','Tramadol HCl'),
  (300,'rand','Lyrica'),

  (301,'kip','Alendronate Sodium'),
  (302,'naira','Tramadol HCl'),
  (303,'lira','TriNessa'),
  (304,'yen','Amitriptyline HCl'),
  (305,'rial','Amphetamine Salts'),
  (306,'pula','Tricor'),
  (307,'ouguiya','Penicillin VK'),
  (308,'rand','Bystolic'),
  (309,'cedi','Sulfamethoxazole/Trimethoprim'),
  (310,'boliviano','Zyprexa'),

  (311,'forint','Glipizide'),
  (312,'dram','Lantus Solostar'),
  (313,'shekel','Lorazepam'),
  (314,'koruna','Suboxone'),
  (315,'yuan','Amitriptyline HCl'),
  (316,'koruna','Diovan'),
  (317,'zloty','Paroxetine HCl'),
  (318,'bolivar','Niaspan'),
  (319,'shekel','Benicar HCT'),
  (320,'real','Fluoxetine HCl'),

  (321,'pataca','Suboxone'),
  (322,'peso','Sertraline HCl'),
  (323,'lira','Cephalexin'),
  (324,'kina','Ciprofloxacin HCl'),
  (325,'manat','Cialis'),
  (326,'quetzal','Nexium'),
  (327,'kuna','Metoprolol Succinate'),
  (328,'kwacha','Lexapro'),
  (329,'peso','Metformin HCl'),
  (330,'Danish krone','Nasonex'),

  (331,'real','Abilify'),
  (332,'ouguiya','Potassium Chloride'),
  (333,'euro','Simvastatin'),
  (334,'rufiyaa','Venlafaxine HCl ER'),
  (335,'dram','Fluoxetine HCl'),
  (336,'dong','Vyvanse'),
  (337,'leu','Amitriptyline HCl'),
  (338,'pound','Zyprexa'),
  (339,'pound','Diovan'),
  (340,'koruna','Fluoxetine HCl'),

  (341,'rouble','Amphetamine Salts'),
  (342,'ariary','Namenda'),
  (343,'pound','Fluconazole'),
  (344,'rand','Lyrica'),
  (345,'kuna','APAP/Codeine'),
  (346,'naira','Lorazepam'),
  (347,'rouble','Atenolol'),
  (348,'sum','Azithromycin'),
  (349,'escudo','Flovent HFA'),
  (350,'pula','Loestrin 24 Fe'),

  (351,'colon','LevothyroxineSodium'),
  (352,'rupiah','Furosemide'),
  (353,'peso','Synthroid'),
  (354,'rouble','Gabapentin'),
  (355,'franc','Loestrin 24 Fe'),
  (356,'won','Warfarin Sodium'),
  (357,'baht','Namenda'),
  (358,'bolivar','Glipizide'),
  (359,'baht','TriNessa'),
  (360,'kwanza','Nexium'),

  (361,'sum','Spiriva Handihaler'),
  (362,'escudo','Paroxetine HCl'),
  (363,'ringgit','Simvastatin'),
  (364,'kuna','Triamcinolone Acetonide'),
  (365,'shekel','Carisoprodol'),
  (366,'riyal','Risperidone'),
  (367,'konvertibilna marka','Viagra'),
  (368,'guarani','Lantus'),
  (369,'bolivar','Venlafaxine HCl ER'),
  (370,'rufiyaa','Lantus'),

  (371,'manat','Triamcinolone Acetonide'),
  (372,'rupee','Symbicort'),
  (373,'peso','Benicar'),
  (374,'som','Cyclobenzaprin HCl'),
  (375,'rufiyaa','Tamsulosin HCl'),
  (376,'pula','Oxycontin'),
  (377,'peso','Amoxicillin Trihydrate/Potassium Clavulanate'),
  (378,'riel','Proair HFA'),
  (379,'franc','Methylprednisolone'),
  (380,'dirham','Levaquin'),

  (381,'dong','Hydrocodone/APAP'),
  (382,'manat','Proair HFA'),
  (383,'konvertibilna marka','Pantoprazole Sodium'),
  (384,'lilangeni','Promethazine HCl'),
  (385,'krona','Suboxone'),
  (386,'colon',''),
  (387,'pound','Fluticasone Propionate'),
  (388,'ariary','Advair Diskus'),
  (389,'lev','Tramadol HCl'),
  (390,'baht','Fluoxetine HCl'),

  (391,'rupee','Sulfamethoxazole/Trimethoprim'),
  (392,'ringgit','Furosemide'),
  (393,'rial','Tri-Sprintec'),
  (394,'manat','Enalapril Maleate'),
  (395,'real','Synthroid'),
  (396,'hryvnia','Lidoderm'),
  (397,'leu','Singulair'),
  (398,'hryvnia','Hydrocodone/APAP'),
  (399,'yen','Zyprexa'),
  (400,'sum','Singulair'),

  (401,'ouguiya','Flovent HFA'),
  (402,'cedi','Proair HFA'),
  (403,'guarani','Warfarin Sodium'),
  (404,'nuevo sol','Suboxone'),
  (405,'dinar','Hydrocodone/APAP'),
  (406,'shekel','Sulfamethoxazole/Trimethoprim'),
  (407,'riel','Amoxicillin'),
  (408,'dong','Namenda'),
  (409,'lek','Proair HFA'),
  (410,'riyal','Metformin HCl'),

  (411,'tugrik','Celebrex'),
  (412,'pound','Zolpidem Tartrate'),
  (413,'koruna','Vitamin D (Rx)'),
  (414,'rufiyaa','Lantus'),
  (415,'metical','Oxycontin'),
  (416,'real','Crestor'),
  (417,'dirham','Clindamycin HCl'),
  (418,'tenge','Clonazepam'),
  (419,'leu','Fluconazole'),
  (420,'hryvnia','Sertraline HCl'),

  (421,'sterling','Omeprazole (Rx)'),
  (422,'zloty','Oxycodone HCl'),
  (423,'kip','Tramadol HCl'),
  (424,'yuan','Lovaza'),
  (425,'dram','Suboxone'),
  (426,'lari','Lexapro'),
  (427,'sum','Symbicort'),
  (428,'dirham','Tricor'),
  (429,'cordoba oro','Ventolin HFA'),
  (430,'nuevo sol','Nexium'),

  (431,'dirham','Loestrin 24 Fe'),
  (432,'kroner','Celebrex'),
  (433,'ouguiya','Cheratussin AC'),
  (434,'hryvnia','Singulair'),
  (435,'leu','Metoprolol Succinate'),
  (436,'rufiyaa','Pantoprazole Sodium'),
  (437,'pataca','Citalopram HBr'),
  (438,'leu','Glyburide'),
  (439,'somoni','Tramadol HCl'),
  (440,'pound','Lorazepam'),

  (441,'lari','Amoxicillin Trihydrate/Potassium Clavulanate'),
  (442,'dram','Venlafaxine HCl ER'),
  (443,'ouguiya','Lantus'),
  (444,'escudo','Prednisone'),
  (445,'kwacha','Lisinopril'),
  (446,'escudo','Folic Acid'),
  (447,'quetzal','Glyburide'),
  (448,'rial','Vytorin'),
  (449,'zloty','Proair HFA'),
  (450,'Danish krone','Amoxicillin Trihydrate/Potassium Clavulanate'),

  (451,'dirham','Diovan'),
  (452,'ringgit','Alprazolam'),
  (453,'rupiah','Oxycodone/APAP'),
  (454,'yen','Lantus Solostar'),
  (455,'yen','Amoxicillin Trihydrate/Potassium Clavulanate'),
  (456,'colon','Zolpidem Tartrate'),
  (457,'metical','Cymbalta'),
  (458,'baht','Crestor'),
  (459,'rufiyaa',''),
  (460,'shekel','Lyrica'),

  (461,'som','Actos'),
  (462,'quetzal','Niaspan'),
  (463,'krona','Prednisone'),
  (464,'konvertibilna marka','Cialis'),
  (465,'nuevo sol','Paroxetine HCl'),
  (466,'dollar','Tramadol HCl'),
  (467,'sterling','Diovan'),
  (468,'lari','Citalopram HBr'),
  (469,'kwanza','Sulfamethoxazole/Trimethoprim'),
  (470,'koruna','Nuvaring'),

  (471,'lek','Oxycodone/APAP'),
  (472,'riyal','Pravastatin Sodium'),
  (473,'peso','Lorazepam'),
  (474,'guarani','Cymbalta'),
  (475,'ariary','Lidoderm'),
  (476,'riyal','Nasonex'),
  (477,'colon','Digoxin'),
  (478,'denar','Tricor'),
  (479,'kina','Glipizide'),
  (480,'manat','Synthroid'),

  (481,'cedi','Hydrochlorothiazide'),
  (482,'sterling','Namenda'),
  (483,'ringgit','Vytorin'),
  (484,'rufiyaa','Hydrochlorothiazide'),
  (485,'rupiah','Fluoxetine HCl'),
  (486,'tenge','Lyrica'),
  (487,'Danish krone','Flovent HFA'),
  (488,'rupiah','Pantoprazole Sodium'),
  (489,'tenge','Namenda'),
  (490,'won','Singulair'),

  (491,'pound','Lidoderm'),
  (492,'pula','Fluconazole'),
  (493,'yen','Sertraline HCl'),
  (494,'leu','Symbicort'),
  (495,'real','Celebrex'),
  (496,'som','Januvia'),
  (497,'kuna','Tamsulosin HCl'),
  (498,'lari','Tamsulosin HCl'),
  (499,'shekel','Citalopram HBr'),
  (500,'kip','Alendronate Sodium');
